name: Package and Release on PyPI
on:
  push:
    tags:
      - "*"
  package:
    needs: test-easyauth
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set Tag for RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Packaging dependencies
        run: |
          pip install wheel twine

      - name: Package & Test PyPI Installation
        run: |
          export NEXTVERSION=${{ env.RELEASE_VERSION }}
          sed -i 's/NEXTVERSION/'$NEXTVERSION'/g' setup.py
          python setup.py bdist_wheel
          export PYQL_PACKAGE=$(pwd)/dist/easy_auth-$NEXTVERSION-py3-none-any.whl
          pip install $(echo -n $PYQL_PACKAGE)

      - name: Upload to PyPi
        env: # Or as an environment variable
          PYPI: ${{ secrets.PYPI }}
        run: |
          export NEXTVERSION=${{ env.RELEASE_VERSION }}
          export PYQL_PACKAGE=$(pwd)/dist/easy_auth-$NEXTVERSION-py3-none-any.whl
          python -m twine upload $(pwd)/dist/easy_auth-$NEXTVERSION-py3-none-any.whl -u codemation -p $PYPI
  docker_build:
    needs: package
    name: Create Docker Image and Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set Tag for RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push EasyAuth Docker Image
        run: |
          export NEXTVERSION=${{ env.RELEASE_VERSION }}
          docker build docker/docker/ -t joshjamison/easyauth:$NEXTVERSION
          docker push joshjamison/easyauth:$NEXTVERSION